name: Build and Deploy CV
on:
  repository_dispatch:
    types: [ data_updated ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Engine
        uses: actions/checkout@v4

      - name: Clone Private Data
        run: git clone https://${{ secrets.PAT_TOKEN }}@github.com/Ciamma/my-cv-data.git data

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: false
          
      - name: DEBUG - Check Go Modules
        run: |
          echo "Running 'go mod tidy'..."
          go mod tidy

      - name: Build Static Site
        run: |
          echo "Running 'go run main.go'..."
          go run main.go -export

      # NUOVA PROCEDURA PER IL PDF
      - name: Setup Node.js (per Paged.js)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Paged.js CLI
        run: npm install pagedjs-cli --no-package-lock

      - name: Generate PDF
        run: npx pagedjs-cli dist/pdf.html -o dist/curriculum.pdf --browserArgs --no-sandbox

      - name: Encrypt PDF and Clean Up
        run: |
          sudo apt-get update && sudo apt-get install -y qpdf
          qpdf --encrypt "${{ secrets.PDF_PASSWORD }}" "${{ secrets.PDF_PASSWORD }}" 256 -- dist/curriculum.pdf dist/curriculum-encrypted.pdf
          mv dist/curriculum-encrypted.pdf dist/curriculum.pdf
          rm dist/pdf.html

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4